
name: "stork-tasks"

domain: "co.fizzed.stork"

display_name: "Stork Launcher Generator by Fizzed"

short_description: "Utility for creating scripts to launch Java apps"

type: CONSOLE

main_class: "co.fizzed.stork.tasks.TasksMain"

java_args: "-Dscala.usejavacp=true"

platforms: [ WINDOWS, LINUX ]

working_dir_mode: RETAIN
  
min_java_version: "1.4"

symlink_java: false